# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# ------
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.2.13
# In script commands below we will do following stuff: 
# installing YAML file configuration
# installing composer and setting up environment variable
# installing Git FTP service without "y/n" answer requirements

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - yum -y update && yum install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - git-ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_HOST_PATH